/* Writes sitemap.xml and robots.txt from data.js. Needs SITE.url set. */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

// run data.js in a function scope and pull the bindings out
const src = readFileSync(join(root, "assets/js/data.js"), "utf8");
const { SITE, PROJECTS, POSTS } = new Function(
  `${src}\nreturn { SITE, PROJECTS, POSTS };`
)();

const base = (SITE.url || "").replace(/\/+$/, "");
if (!base) {
  console.error(
    "SITE.url is empty in assets/js/data.js.\n" +
    'Set it to your live address (e.g. "https://yourname.dev") and run this again.'
  );
  process.exit(1);
}

const today = new Date().toISOString().slice(0, 10);

/* Priority is a hint, not a ranking. Home and the work pages lead. */
const pages = [
  { loc: "",              changefreq: "monthly", priority: "1.0" },
  { loc: "projects.html", changefreq: "monthly", priority: "0.9" },
  { loc: "about.html",    changefreq: "yearly",  priority: "0.8" },
  { loc: "devlog.html",   changefreq: "weekly",  priority: "0.8" },
  { loc: "services.html", changefreq: "yearly",  priority: "0.7" },
  { loc: "gallery.html",  changefreq: "monthly", priority: "0.6" },
  { loc: "resume.html",   changefreq: "yearly",  priority: "0.6" },
  { loc: "contact.html",  changefreq: "yearly",  priority: "0.5" }
];

const urls = [
  ...pages.map((p) => ({ ...p, loc: `${base}/${p.loc}`, lastmod: today })),

  ...PROJECTS.map((p) => ({
    loc: `${base}/project.html?p=${encodeURIComponent(p.slug)}`,
    lastmod: today,
    changefreq: "yearly",
    priority: p.featured ? "0.8" : "0.6"
  })),

  ...POSTS.slice()
    .sort((a, b) => (a.date < b.date ? 1 : -1))
    .map((p) => ({
      loc: `${base}/post.html?id=${encodeURIComponent(p.slug)}`,
      lastmod: p.date,
      changefreq: "yearly",
      priority: "0.6"
    }))
];

const xmlEscape = (s) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

const sitemap =
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<!-- generated by tools/gen-sitemap.mjs -->\n` +
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
  urls
    .map(
      (u) =>
        `  <url>\n` +
        `    <loc>${xmlEscape(u.loc)}</loc>\n` +
        `    <lastmod>${u.lastmod}</lastmod>\n` +
        `    <changefreq>${u.changefreq}</changefreq>\n` +
        `    <priority>${u.priority}</priority>\n` +
        `  </url>`
    )
    .join("\n") +
  `\n</urlset>\n`;

const robots =
  `# Generated by tools/gen-sitemap.mjs. Do not edit by hand.\n` +
  `User-agent: *\n` +
  `Allow: /\n\n` +
  `Sitemap: ${base}/sitemap.xml\n`;

writeFileSync(join(root, "sitemap.xml"), sitemap, "utf8");
writeFileSync(join(root, "robots.txt"), robots, "utf8");

console.log(`sitemap.xml  ${urls.length} URLs`);
console.log(`robots.txt   sitemap -> ${base}/sitemap.xml`);
